image: Visual Studio 2017
version: 0.0.0.{build}
platform: Any CPU
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)

environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
  codesignaes:
    secure: 9f78dD9jN5vlVZ0zv15kdD4Mj+/+uacfu29bbGC+cBVFs834aFVf5Ci+n3NP3Bl7
  codesignpasswd:
    secure: iKv14aGuHUDEfb5fSIBMuSsu1JnisWXL8wJ7x/2DCNtggWKevjhOFBOrI7c95xBY

cache:
  - packages

install:
  - ps: ./CI/appveyor_install.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /t:Clean /v:q /nologo

build_script:
  - ps: msbuild /nologo /v:q /p:Configuration="$env:CONFIGURATION" /p:SquirrelBuildTarget="$env:DEPLOY_SITE_GIT\Recorder"


for:

-
  branches:
    only:
      - master
  configuration: Release
  artifacts:
  before_deploy:
    - ps: ./CI/appveyor_deploy.ps1
  deploy:
    provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: '# Fill out this before publish'
    auth_token:
      secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
    artifact: github
    draft: true

-
  configuration: Debug
  artifacts:
    - path: BililiveRecorder.WPF\bin\Debug
      name: BililiveRecorderDebugBuild

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
